[package]
authors = ["Edward Yang <edward.yang6771@gmail.com>"]
name = "visualizers"
version = "0.1.0"

[dependencies]
cairo-rs = "*"
dft = "0.4.3"
gdk = "*"
gtk = "*"
pulse-simple = {git = "https://github.com/efyang/rust-pulse-simple"}
